/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import collectionTypeSuite from "./collection-ti";
// tslint:disable:object-literal-key-quotes

export const IAligner = t.iface(["ICollection"], {
  axis: "Dimensions",
  bindMainAxis: "boolean",
  alignment: "Alignment",
  minCrossAxis: t.opt("number")
});

const alignerTypeSuite: t.ITypeSuite = {
  IAligner,
  ...collectionTypeSuite
};
export default alignerTypeSuite;
