/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import lineTypeSuite from "./line-ti";
// tslint:disable:object-literal-key-quotes

export const HeadStyle = t.union(t.lit("default"), t.lit("thin"), t.lit("none"));

export const IArrowStyle = t.iface([], {
  "headStyle": "HeadStyle",
});

export const IArrow = t.iface(["ILine"], {
  "arrowStyle": "IArrowStyle",
});

const arrowTypeSuite: t.ITypeSuite = {
  HeadStyle,
  IArrowStyle,
  IArrow,
  ...lineTypeSuite
};
export default arrowTypeSuite;
