/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import collectionTypeSuite from "./collection-ti";
// tslint:disable:object-literal-key-quotes

export const ChannelNamedStructure = t.union(
  t.lit("top aligner"),
  t.lit("bottom aligner"),
  t.lit("bar")
);

export const IChannel = t.iface(["ICollection"], {
  mountedElements: t.array("IVisual"),
  sequenceID: "ID",
  style: "IChannelStyle",
  channelSymbol: "IText"
});

export const IChannelStyle = t.iface([], {
  thickness: "number",
  barStyle: "IRectStyle"
});

const channelTypeSuite: t.ITypeSuite = {
  ChannelNamedStructure,
  IChannel,
  IChannelStyle,
  ...collectionTypeSuite
};
export default channelTypeSuite;
