/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import visualTypeSuite from "./Visual-ti";
// tslint:disable:object-literal-key-quotes

export const ICollection = t.iface(["IVisual"], {
});

const collectionTypeSuite: t.ITypeSuite = {
  ICollection,
  ...visualTypeSuite
};
export default collectionTypeSuite;
