/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import collectionTypeSuite from "./collection-ti";
// tslint:disable:object-literal-key-quotes

export const IDiagram = t.iface(["ICollection"], {
  sequences: t.array("ISequence")
});

export const DiagramNamedStructure = t.union(t.lit("sequence column"), t.lit("root"));

export const AllStructures = t.union(
  "SequenceNamedStructure",
  "ChannelNamedStructure",
  "DiagramNamedStructure"
);

const diagramTypeSuite: t.ITypeSuite = {
  IDiagram,
  DiagramNamedStructure,
  AllStructures,
  ...collectionTypeSuite
};
export default diagramTypeSuite;
