/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import collectionTypeSuite from "./collection-ti";
// tslint:disable:object-literal-key-quotes

export const ILabelGroup = t.iface(["ICollection"], {
  "labels": t.array("ILabel"),
  "coreChild": "IVisual",
});

const labelGroupTypeSuite: t.ITypeSuite = {
  ILabelGroup,
  ...collectionTypeSuite
};
export default labelGroupTypeSuite;
