/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import collectionTypeSuite from "./collection-ti";
// tslint:disable:object-literal-key-quotes

export const LabelTextPosition = t.union(t.lit("top"), t.lit("bottom"), t.lit("inline"));

export const ILabelConfig = t.iface([], {
	labelPosition: "Position",
	textPosition: "LabelTextPosition"
});

export const ILabel = t.iface(["ICollection"], {
	text: t.opt("IText"),
	line: t.opt("IArrow"),
	labelConfig: "ILabelConfig"
});

const labelTypeSuite: t.ITypeSuite = {
	LabelTextPosition,
	ILabelConfig,
	ILabel,
	...collectionTypeSuite
};
export default labelTypeSuite;
