/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Orientation = t.union(t.lit("horizontal"), t.lit("vertical"), t.lit("angled"));

export const ILineLike = t.iface(["IVisual"], {
  adjustment: t.tuple("number", "number"),
  orientation: "Orientation"
});

const lineLikeTypeSuite: t.ITypeSuite = {
  Orientation,
  ILineLike
};
export default lineLikeTypeSuite;
