/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import lineLikeTypeSuite from "./lineLike-ti";
// tslint:disable:object-literal-key-quotes

export const ILine = t.iface(["ILineLike"], {
  style: "lineStyle"
});

export const lineStyle = t.iface([], {
  stroke: "string",
  thickness: "number",
  dashing: t.tuple("number", "number")
});

const lineTypeSuite: t.ITypeSuite = {
  ILine,
  lineStyle,
  ...lineLikeTypeSuite
};
export default lineTypeSuite;
