/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import spaceTypeSuite from "./spacial-ti";
// tslint:disable:object-literal-key-quotes

export const Padding = t.union("number", t.tuple("number", "number"), t.tuple("number", "number", "number", "number"));

export const Offset = t.tuple("number", "number");

export const Dim = t.iface([], {
  "width": t.opt("number"),
  "height": t.opt("number"),
});

export const Bounds = t.iface([], {
  "top": "number",
  "bottom": "number",
  "left": "number",
  "right": "number",
});

export const IPaddedBox = t.iface(["ISpacial"], {
  "padding": t.tuple("number", "number", "number", "number"),
});

const paddedBoxTypeSuite: t.ITypeSuite = {
  Padding,
  Offset,
  Dim,
  Bounds,
  IPaddedBox,
  ...spaceTypeSuite
};
export default paddedBoxTypeSuite;
