/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ID = t.name("string");

export const Shift = t.iface([], {
  dx: t.opt("number"),
  dy: t.opt("number")
});

export const Place = t.iface([], {
  x: t.opt("number"),
  y: t.opt("number")
});

export const IElement = t.iface([], {
  ref: "string",
  id: t.opt("ID")
});

export const IPoint = t.iface(["IElement"], {
  x: t.opt("number"),
  y: t.opt("number")
});

export const IStateTarget = t.iface([], {});

const pointTypeSuite: t.ITypeSuite = {
  ID,
  Shift,
  Place,
  IElement,
  IPoint,
  IStateTarget
};
export default pointTypeSuite;
