/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import visualTypeSuite from "./Visual-ti";
// tslint:disable:object-literal-key-quotes

export const IRectStyle = t.iface([], {
  fill: "string",
  stroke: t.union("string", "null"),
  strokeWidth: t.union("number", "null")
});

export const IRectElement = t.iface(["IVisual"], {
  style: "IRectStyle"
});

const rectElementTypeSuite: t.ITypeSuite = {
  IRectStyle,
  IRectElement,
  ...visualTypeSuite
};
export default rectElementTypeSuite;
