/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import collectionTypeSuite from "./collection-ti";
// tslint:disable:object-literal-key-quotes

export const ISequence = t.iface(["ICollection"], {
	channels: t.array("IChannel")
});

export const OccupancyStatus = t.union("Visual", t.lit("."), "undefined");

export const SequenceNamedStructures = t.union(
	t.lit("channel column"),
	t.lit("label column"),
	t.lit("label col | pulse columns"),
	t.lit("pulse columns")
);

const sequenceTypeSuite: t.ITypeSuite = {
	ISequence,
	OccupancyStatus,
	SequenceNamedStructures,
	...collectionTypeSuite
};
export default sequenceTypeSuite;
