/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
import visualTypeSuite from "./Visual-ti";
// tslint:disable:object-literal-key-quotes

export const ISpace = t.iface(["IVisual"], {});

const spaceTypeSuite: t.ITypeSuite = {
  ISpace,
  ...visualTypeSuite
};
export default spaceTypeSuite;
