/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login or create account with Google OAuth credentials */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Credentials returned by Google OAuth flow */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["loginCredentialsRequest"];
                };
            };
            responses: {
                /** @description OK - session is now authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["genericResponse"];
                    };
                };
                /** @description Malformed or invalid form data from 'sign on with google' */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/diagrams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of diagrams belonging to the logged in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK - a list of diagrams is returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["diagramsListResponse"];
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/schemes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of schemes belonging to the logged in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK - a list of schemes is returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["schemesListResponse"];
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user data from the current session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK - user data retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["meResponse"];
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagrams/{diagramId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load the specified diagram */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Diagram Id */
                    diagramId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK - the specified diagram data is returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": components["schemas"]["diagramDataResponse"];
                    };
                };
                /** @description Malformed diagram Id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Diagram not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Save the diagram data
         * @description Saves the diagram JSON to the database based on the current user.<br> **Users saving their own diagram** have the changes committed.<br> **Users saving someone elses diagram** make a copy of the diagram and commit the changes to their owned copy.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Diagram Id */
                    diagramId: string;
                };
                cookie?: never;
            };
            /** @description A nmrd diagram file to save. */
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                        data?: string;
                    };
                };
            };
            responses: {
                /** @description OK - saving/copying has been successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["saveDiagramResponse"] | components["schemas"]["copyDiagramResponse"];
                    };
                };
                /** @description Malformed diagram Id/body is not a JSON object */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication Required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The logged in user does not have permission to delete this diagram */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Diagram not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete the specified diagram belonging to the logged in user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Diagram Id */
                    diagramId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK - the diagram has been successfully deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["genericResponse"];
                    };
                };
                /** @description Malformed diagram Id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication Required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The logged in user does not have permission to delete this diagram */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Diagram not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagrams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a diagram belonging to the logged in user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The name given to the newly created diagram and the nmrd file */
            requestBody: {
                content: {
                    "multipart/form-data": {
                        name?: string;
                        /** Format: binary */
                        file?: string;
                        data?: string;
                    };
                };
            };
            responses: {
                /** @description OK - a blank diagram has been created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["diagramCreateResponse"];
                    };
                };
                /** @description Malformed request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication Required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagrams/{diagramId}/modified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets the last date modified for the specified diagram */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Diagram Id */
                    diagramId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK - the date modified is returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            date_modified?: string;
                        };
                    };
                };
                /** @description Malformed diagram Id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Diagram not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemes/{schemeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load the specified scheme */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Scheme Id */
                    schemeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK - the specified scheme data is returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": components["schemas"]["schemeDataResponse"];
                    };
                };
                /** @description Malformed scheme Id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Scheme not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Save the scheme data */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Scheme Id */
                    schemeId: string;
                };
                cookie?: never;
            };
            /** @description A nmrs scheme file to save. */
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK - saving has been successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["saveSchemeResponse"];
                    };
                };
                /** @description Malformed scheme Id/body is not a JSON object */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication Required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Scheme not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Create a scheme belonging to the logged in user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Scheme Id */
                    schemeId: string;
                };
                cookie?: never;
            };
            /** @description The name given to the newly created scheme and the nmrs file */
            requestBody: {
                content: {
                    "multipart/form-data": {
                        name?: string;
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK - a blank scheme has been created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["schemeCreateResponse"];
                    };
                };
                /** @description Malformed request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication Required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Delete the specified scheme belonging to the logged in user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Scheme Id */
                    schemeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK - the scheme has been successfully deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["genericResponse"];
                    };
                };
                /** @description Malformed scheme Id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication Required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Scheme not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        genericResponse: {
            message?: string;
        };
        diagramsListResponse: {
            diagrams?: {
                /** Format: uuid */
                diagram_id?: string;
                name?: string;
                /** Format: date-time */
                dateCreated?: string;
                institution?: string;
                originalAuthor?: string;
            }[];
        };
        schemesListResponse: {
            schemes?: {
                /** Format: uuid */
                scheme_id?: string;
                name?: string;
            }[];
        };
        meResponse: {
            email?: string;
            firstname?: string;
            gsub?: string;
            picture?: null | string;
            surname?: string;
        };
        loginCredentialsRequest: {
            credential?: string;
            clientId?: string;
            select_by?: string;
        };
        /** Format: binary */
        diagramDataResponse: string;
        diagramCreateResponse: {
            message?: string;
            /**
             * Format: uuid
             * @description The diagram Id of the newly created diagram
             */
            id?: string;
        };
        copyDiagramResponse: {
            message?: string;
            /**
             * Format: uuid
             * @description The diagram Id of the newly created diagram
             */
            savedDiagramId?: string;
            copied?: boolean;
        };
        saveDiagramResponse: {
            message?: string;
            copied?: boolean;
        };
        schemeMetadata: {
            name?: string;
        };
        /** Format: binary */
        schemeDataResponse: string;
        schemeCreateResponse: {
            message?: string;
            /**
             * Format: uuid
             * @description The scheme Id of the newly created scheme
             */
            id?: string;
        };
        saveSchemeResponse: {
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
