/* eslint-disable @typescript-eslint/consistent-type-definitions */
/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Diagrams {
  data: Json;
  date_created: Timestamp;
  date_modified: Timestamp;
  diagram_id: string;
  name: string;
  owner: string;
  institution: string | null;
  original_author: string | null;
}

export interface Schemes {
  date_created: Timestamp;
  date_modified: Timestamp;
  name: string;
  owner: string;
  scheme_id: string;
}

export interface Users {
  email: string;
  firstname: string;
  gsub: string;
  picture: string | null;
  surname: string;
}

export interface DB {
  diagrams: Diagrams;
  schemes: Schemes;
  users: Users;
}
